### ISSUE TITLE
Carry flash messages across redirect

### ISSUE THREAD

**Issue by diggersworld** [spatie/laravel-flash#11]
In my codebase I have the following code:

```php
public function destroy(DeleteResourceRequest $request, string $resource_uuid)
{
     // delete resource...

     flash()->success('Resource was deleted');

     return redirect('admin/resources');
}
```

However, after the redirect, the flash message has disappeared. Is there a way to carry the message over the redirect?

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that could address this problem.

**Comment by diggersworld** [comment]
Here's what Laravel has to say about redirecting with flashed session data: https://laravel.com/docs/5.8/redirects#redirecting-with-flashed-session-data

**Comment by diggersworld** [comment]
Ah! The problem I'm experiencing is only in tests, probably because the session is array based, and on redirect its reset. I'll close this issue.
