### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by danabrey** [spatie/laravel-flash#17]
Hey! Thanks for this lightweight package, I've enjoyed using it on a few projects. Quick question: is there a way to use dependency injection for creating flash messages instead of the global `flash()` helper?

**Comment by freekmurze** [comment]
You could inject the `Flash` class and then use it like it's being used in the `flash` function.

https://github.com/spatie/laravel-flash/blob/master/src/helpers.php#L12-L23
