### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by ualmousa** [spatie/laravel-flash#18]
Hello,

Release note of v1.4.0 is "drop support for PHP 7.3"

I was wondering why this package would drop support for PHP 7.3 this early.
Or was it just a typo I hope? 😅

**Comment by freekmurze** [comment]
We like to use PHP7.4 typed properties and are using those now in this package.


You can still use an older version of the package if you want.

**Comment by basepack** [comment]
@freekmurze when using this package at version 1.3 with PHP7.3, Laravel 7.0 we get errors like this:

```
spatie/laravel-flash 1.3.0 requires illuminate/session ^5.5|^5.6|^5.7|^5.8|^6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x
-dev],
```

**Comment by sergiz** [comment]
I also think that raising the PHP requirement just because of 4! typed properties seems kinda unjustifiable :/
