### ISSUE TITLE
Use HTML in flash message?

### ISSUE THREAD

**Issue by minthemiddle** [spatie/laravel-flash#21]
Is there any way to pass a link within the flash message? When I pass HTML, such as `flash('Registration failed. Please <a href="#">contact admin</a>'));`, the HTML is shown verbatim.

**Comment by freekmurze** [comment]
The flash package doesn't modify the content of the flash.

Did you try rendering with `{{! !}}` already?

**Comment by minthemiddle** [comment]
`{!! flash()->message !!}` works. Thanks!
