### ISSUE TITLE
Followed docs but getting error

### ISSUE THREAD

**Issue by GigaMick** [spatie/laravel-flash#23]
I've installed the package via composer.

Then all I've done is add

```flash('My message');```

into my function. Here is the entire function

```
public function sms(Request $request)
    {

        $message = $request->email." -- ".$request->phone." -- ".$request->message;

        $sms = new SendText();
        $sms->sendsms("+xxxxxxxxxxx", $message);

        flash('My message');

        return back();
    }
```

I'm getting the following error:

> Symfony\Component\Debug\Exception\FatalThrowableError
> syntax error, unexpected 'Session' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

<img width="1016" alt="Screenshot 2020-05-20 at 22 29 28" src="https://user-images.githubusercontent.com/22120297/82499318-66254f00-9ae9-11ea-906e-650bb3b80282.png">

**Comment by freekmurze** [comment]
This package requires PHP 7.4, and it seems you are not running that.
