### ISSUE TITLE
Is there a way you may show the flash message once?

### ISSUE THREAD

**Issue by pakogn** [spatie/laravel-flash#9]
Is there a way you may show the flash message once?

I mean, for first you are in the contact route, you submit the contact form and a redirect to a success route is done. So in this success route a "flash" alert appears, then you press a link to other route and finally you press browser's back button and the flash is triggered again. Is there a way to avoid this behavior?

Greetings!

**Comment by freekmurze** [comment]
You can't avoid this behaviour with this package. You're seeing the flash message again because your browser gets the html from cache and that html has the message.

Maybe you could detect with JS that you're going back and hide the message, but that's beyond the scope if this package.

**Comment by pakogn** [comment]
Is there any workaround or will this package support this in the future?

beg your pardon for asking again.

Thanks

**Comment by freekmurze** [comment]
No, we will not support this in the future.
